#pragma once

namespace OK
{
    enum class EKeyboardKey
    {
        LButton         = VK_LBUTTON,
        RButton         = VK_RBUTTON,
        Cancel          = VK_CANCEL,
        MButton         = VK_MBUTTON,

        Back            = VK_BACK,
        Tab             = VK_TAB,
        Clear           = VK_CLEAR,
        Return          = VK_RETURN,

        Shift           = VK_SHIFT,
        Control         = VK_CONTROL,
        Menu            = VK_MENU,
        Pause           = VK_PAUSE,
        Capital         = VK_CAPITAL,
        Escape          = VK_ESCAPE,

        Space           = VK_SPACE,
        Prior           = VK_PRIOR,
        Next            = VK_NEXT,
        End             = VK_END,
        Home            = VK_HOME,
        Left            = VK_LEFT,
        Up              = VK_UP,
        Right           = VK_RIGHT,
        Down            = VK_DOWN,
        Select          = VK_SELECT,
        Print           = VK_PRINT,
        Execute         = VK_EXECUTE,
        Snapshot        = VK_SNAPSHOT,
        Insert          = VK_INSERT,
        Delete          = VK_DELETE,
        Help            = VK_HELP,

        Key_0           = '0',
        Key_1           = '1',
        Key_2           = '2',
        Key_3           = '3',
        Key_4           = '4',
        Key_5           = '5',
        Key_6           = '6',
        Key_7           = '7',
        Key_8           = '8',
        Key_9           = '9',

        Key_A           = 'A',
        Key_B           = 'B',
        Key_C           = 'C',
        Key_D           = 'D',
        Key_E           = 'E',
        Key_F           = 'F',
        Key_G           = 'G',
        Key_H           = 'H',
        Key_I           = 'I',
        Key_J           = 'J',
        Key_K           = 'K',
        Key_L           = 'L',
        Key_M           = 'M',
        Key_N           = 'N',
        Key_O           = 'O',
        Key_P           = 'P',
        Key_Q           = 'Q',
        Key_R           = 'R',
        Key_S           = 'S',
        Key_T           = 'T',
        Key_U           = 'U',
        Key_V           = 'V',
        Key_W           = 'W',
        Key_X           = 'X',
        Key_Y           = 'Y',
        Key_Z           = 'Z',

        LWindows        = VK_LWIN,
        RWindows        = VK_RWIN,
        Apps            = VK_APPS,
        Sleep           = VK_SLEEP,

        Numpad_0        = VK_NUMPAD0,
        Numpad_1        = VK_NUMPAD1,
        Numpad_2        = VK_NUMPAD2,
        Numpad_3        = VK_NUMPAD3,
        Numpad_4        = VK_NUMPAD4,
        Numpad_5        = VK_NUMPAD5,
        Numpad_6        = VK_NUMPAD6,
        Numpad_7        = VK_NUMPAD7,
        Numpad_8        = VK_NUMPAD8,
        Numpad_9        = VK_NUMPAD9,

        Multiply        = VK_MULTIPLY,
        Add             = VK_ADD,
        Separator       = VK_SEPARATOR,
        Substract       = VK_SUBTRACT,
        Decimal         = VK_DECIMAL,
        Divide          = VK_DIVIDE,

        Key_F1          = VK_F1,
        Key_F2          = VK_F2,
        Key_F3          = VK_F3,
        Key_F4          = VK_F4,
        Key_F5          = VK_F5,
        Key_F6          = VK_F6,
        Key_F7          = VK_F7,
        Key_F8          = VK_F8,
        Key_F9          = VK_F9,
        Key_F10         = VK_F10,
        Key_F11         = VK_F11,
        Key_F12         = VK_F12,
        Key_F13         = VK_F13,
        Key_F14         = VK_F14,
        Key_F15         = VK_F15,
        Key_F16         = VK_F16,
        Key_F17         = VK_F17,
        Key_F18         = VK_F18,
        Key_F19         = VK_F19,
        Key_F20         = VK_F20,
        Key_F21         = VK_F21,
        Key_F22         = VK_F22,
        Key_F23         = VK_F23,
        Key_F24         = VK_F24,

        NumLock         = VK_NUMLOCK,
        Scroll          = VK_SCROLL,

        LShift          = VK_LSHIFT,
        RShift          = VK_RSHIFT,
        LControl        = VK_LCONTROL,
        RControl        = VK_RCONTROL,
        LMenu           = VK_LMENU,
        RMenu           = VK_RMENU,
    };

    enum class EKeyboardInputEvent
    {
        None,
        KeyUp,
        KeyDown,
    };
}